buildscript {
    ext {
        androidx_activity_version = "1.10.1"
        androidx_appcompat_version = "1.7.0"
        androidx_core_version = "1.15.0"
        androidx_exifinterface_version = "1.4.0"
        androidx_transition_version = "1.5.1"
        constraintlayout_version = "2.2.1"
    }

    repositories {
        mavenCentral()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.0'
        classpath 'com.vanniktech:gradle-maven-publish-plugin:0.31.0'
    }
}

allprojects {
    repositories {
        mavenCentral()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
